### ISSUE TITLE
Windows line ending in entrypoint.sh script

### ISSUE THREAD

**Issue by MathiasVDA** [zazuko/fuseki-geosparql#20] opened 2023-11-16 20:04 UTC
Hello, the [entrypoint](https://github.com/zazuko/fuseki-geosparql/blob/main/entrypoint.sh) script contains Windows line endings. When building and running the dockerfile, you will receive this error: 

`exec /opt/fuseki/entrypoint.sh: no such file or directory`

Changing the line ending to UNIX resolves this

**Comment by ludovicm67** [comment] 2023-11-17 05:19
Hello @MathiasVDA,

Thank you for opening this issue, but this is not a Windows line ending in that case.
It's the last line of the file.
For better diffs, it's recommended to always add an extra new line at the end of the files.
This is also useful for adding other lines easily after.

This is forced by the `.editorconfig` here: https://github.com/zazuko/fuseki-geosparql/blob/a60b232a26bcc04d471f4306c057766931cbffb4/.editorconfig#L9

So I will need to close this issue and the associated PR.

Regarding the issue you have, this looks very strange.
On MacOS and on Linux I don't have any issue to build it, as I'm running MacOS and the CI is using Linux ; it's able to build perfectly at both places.
What kind of system are you using?

**Closed by ludovicm67** 2023-11-17 05:19 UTC

**Comment by MathiasVDA** [comment] 2023-11-17 09:54
Sorry the commit is not clear because git doesn't report a change in line ending. That's also the reason why I needed to make a non functional change in the file (removing the line at the end). The commit also includes the change in line ending and fixes my issue. 

I'm building the image on a windows machine using docker for windows in a linux container environment. So using WSL. 

I come across line ending issues quite a lot in opensource projects. It's also a well known problem:
https://www.google.com/search?client=firefox-b-d&q=line+ending+entrypoint+docker

**Comment by ludovicm67** [comment] 2023-11-17 09:58
Maybe you can try to clone Git repositories using this ` --config core.autocrlf=input` as suggested at the bottom of https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/ ?

(Never tried it, as I'm not working from a Windows machine)

**Comment by MathiasVDA** [comment] 2023-11-17 19:56
Sorry, it seems I'm mistaken. Git on windwos seems to be configured by default with autocrlf=true and that also performs the conversion when **cloning** a project. `git config --global core.autocrlf false` fixed this behaviour.

**Comment by ludovicm67** [comment] 2023-11-18 05:04
Great, happy that you managed to find the cause of your issue! :)
If people encounter the same issue, then if they look for the issues here they might found this one, and thanks to your update they might be able to fix it on their side also.
